### ISSUE TITLE
Is this an R package?

### ISSUE THREAD

**Issue by skhan8** [TIGER-NET/WOIS_rlibs#2]
I was looking to find Lake Chad Basin polygons of water areas. I found this source on GitHub - but it is not straightforward. Can I use this to pull those raster images into R?

**Comment by j08lue** [comment]
@skhan8 No, this is not a standalone R package but a collection of custom and community R packages included in the Water Observation Information System (WOIS).

If you are interested in WOIS, please find more information on the [WOIS website](http://www.tiger.esa.int/page_eoservices_wois.php).

Regarding the data you are looking for, I can unfortunately not point you to a source. If you are looking for polygons, you should search for vector data / shapefiles rather than raster images.

A few links I found when I searched for "lake chad shapefile":

* https://data.humdata.org/dataset/lac-chad-basin-area
* https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-lakes/

**Comment by skhan8** [comment]
I see - thank you. You're right, I am looking for vector/shapefile/geojson data of water polygons for seasonality of the water basin changing for Lake Chad. 
Thanks for the link to WOIS. It looks interesting - but does WOIS make their shapefiles pubically available outside of the WOIS software itself?

**Comment by j08lue** [comment]
WOIS does not provide vector or raster data but rather tools and workflows in QGIS for downloading and processing third-party data.

**Comment by skhan8** [comment]
Thank you for the clarification! I appreciate all of your help.
